WITH TURNOS_BASE AS (
    SELECT 1 AS ID, '03:00' AS HI, '06:59' AS HF FROM DUAL UNION ALL
    SELECT 2, '07:00', '10:59' FROM DUAL UNION ALL
    SELECT 3, '11:00', '14:59' FROM DUAL UNION ALL
    SELECT 4, '15:00', '18:59' FROM DUAL UNION ALL
    SELECT 5, '19:00', '22:59' FROM DUAL UNION ALL
    SELECT 6, '23:00', '02:59' FROM DUAL
),
PARAM AS (
    SELECT SYSDATE AS AGORA FROM DUAL
),
TURNO_ATUAL AS (
    SELECT 
        T.ID,
        CASE 
            WHEN T.ID = 6 AND TO_CHAR(P.AGORA, 'HH24:MI') < '03:00' THEN TRUNC(P.AGORA) - 1
            ELSE TRUNC(P.AGORA)
        END AS DATA_REF_TURNO
    FROM TURNOS_BASE T, PARAM P
    WHERE 
        (T.HI <= TO_CHAR(P.AGORA, 'HH24:MI') AND T.HF >= TO_CHAR(P.AGORA, 'HH24:MI'))
        OR
        (T.HI > T.HF AND (TO_CHAR(P.AGORA, 'HH24:MI') >= T.HI OR TO_CHAR(P.AGORA, 'HH24:MI') <= T.HF))
),
TURNO_ALVO AS (
    SELECT TA.ID, TA.DATA_REF_TURNO FROM TURNO_ATUAL TA
    UNION ALL
    SELECT CASE WHEN TA.ID - 1 < 1 THEN 6 ELSE TA.ID - 1 END,
           CASE WHEN TA.ID - 1 < 1 THEN TA.DATA_REF_TURNO - 1 ELSE TA.DATA_REF_TURNO END
    FROM TURNO_ATUAL TA
    UNION ALL
    SELECT CASE WHEN TA.ID - 2 < 1 THEN 6 + (TA.ID - 2) ELSE TA.ID - 2 END,
           CASE WHEN TA.ID - 2 < 1 THEN TA.DATA_REF_TURNO - 1 ELSE TA.DATA_REF_TURNO END
    FROM TURNO_ATUAL TA
),
RANGES AS (
    SELECT 
        TA.ID,
        TO_DATE(TO_CHAR(TA.DATA_REF_TURNO, 'DD/MM/YYYY') || ' ' || TB.HI, 'DD/MM/YYYY HH24:MI') AS DH_INICIO,
        CASE 
            WHEN TB.HI > TB.HF THEN TO_DATE(TO_CHAR(TA.DATA_REF_TURNO + 1, 'DD/MM/YYYY') || ' ' || TB.HF, 'DD/MM/YYYY HH24:MI')
            ELSE TO_DATE(TO_CHAR(TA.DATA_REF_TURNO, 'DD/MM/YYYY') || ' ' || TB.HF, 'DD/MM/YYYY HH24:MI')
        END AS DH_FIM
    FROM TURNO_ALVO TA
    JOIN TURNOS_BASE TB ON TA.ID = TB.ID
)
SELECT DISTINCT
    A.DT_GERACAO_LOTE AS DT_GERACAO_FULL,
    A.DT_ATEND_LOTE AS DT_ATEND_FULL,
    TO_CHAR(A.DT_GERACAO_LOTE, 'dd/mm/yy hh24:mi') AS DT_GERACAO_LOTE_,
    TO_CHAR(A.DT_ATEND_LOTE, 'dd/mm/yy hh24:mi') AS DT_ATEND_LOTE,
    TO_CHAR(A.DT_LIMITE_INICIO_ATEND, 'dd/mm/yy hh24:mi') AS DT_LIMITE_INICIO_ATEND,
    OBTER_VALOR_DOMINIO(2116, A.IE_STATUS_LOTE) AS DS_STATUS_LOTE,
    A.NR_LOTE_AGRUPAMENTO,
    A.IE_AGRUPAMENTO, 
    A.CD_SETOR_ATENDIMENTO,
    SETOR.DS_SETOR_ATENDIMENTO,
    PF.NM_PESSOA_FISICA AS NM_PACIENTE,
    TO_CHAR(PF.DT_NASCIMENTO, 'dd/mm/yyyy') AS DT_NASCIMENTO,
    SUBSTR(OBTER_DADOS_ATENDIMENTO(M.NR_ATENDIMENTO, 'DE'), 1, 19) AS DT_ENTRADA,
    SUBSTR(OBTER_CONV_CAT_ATENDIMENTO(M.NR_ATENDIMENTO), 1, 255) AS DS_CONVENIO,
    SUBSTR(OBTER_NOME_SETOR(M.CD_SETOR_ATENDIMENTO), 1, 100) AS DS_SETOR,
    SUBSTR(OBTER_UNID_ATEND_SETOR_ATUAL(M.NR_ATENDIMENTO, M.CD_SETOR_ATENDIMENTO, 'U'), 1, 100) AS DS_LEITO,
    A.NR_SEQUENCIA AS NR_LOTE,
    A.NR_PRESCRICAO,
    P.NR_ATENDIMENTO,
    A.NR_SEQ_TURNO,
    SUBSTR(OBTER_DESC_TURNO_DISP(A.NR_SEQ_TURNO), 1, 80) AS DS_TURNO,
    DECODE(A.NR_SEQ_CLASSIF, 6, 'Agora', 9, 'Ataque', 8, 'Especial', 3, 'Normal', A.NR_SEQ_CLASSIF) AS DS_CLASSIFICACAO,
    CASE WHEN (OBTER_SE_LOTE_ACM_SN(A.NR_SEQUENCIA, 'SN') = 'S' OR OBTER_SE_LOTE_ACM_SN(A.NR_SEQUENCIA, 'ACM') = 'S') THEN 'S' ELSE 'N' END AS ACM_SN_FLAG
FROM AP_LOTE A  
INNER JOIN PRESCR_MEDICA M ON (A.NR_PRESCRICAO = M.NR_PRESCRICAO)
LEFT JOIN ATENDIMENTO_PACIENTE P ON (M.NR_ATENDIMENTO = P.NR_ATENDIMENTO)
LEFT JOIN SETOR_ATENDIMENTO_V SETOR ON (SETOR.CD_SETOR_ATENDIMENTO = A.CD_SETOR_ATENDIMENTO)
LEFT JOIN PESSOA_FISICA PF ON (M.CD_PESSOA_FISICA = PF.CD_PESSOA_FISICA)
-- Mantemos os Joins dos itens apenas para que os filtros do WHERE funcionem
INNER JOIN AP_LOTE_ITEM AL ON (AL.NR_SEQ_LOTE = A.NR_SEQUENCIA)
INNER JOIN MATERIAL MAT ON (MAT.CD_MATERIAL = AL.CD_MATERIAL)
WHERE 1=1
    AND A.DT_ATEND_LOTE BETWEEN (SELECT MIN(DH_INICIO) FROM RANGES) AND (SELECT MAX(DH_FIM) FROM RANGES)
    AND EXISTS (
        SELECT 1 FROM RANGES R 
        WHERE TO_DATE(TO_CHAR(A.DT_ATEND_LOTE, 'DD/MM/YYYY') || ' ' || 
              NVL(REGEXP_SUBSTR(OBTER_HORARIO_ITEM_LOTE(A.NR_SEQUENCIA, AL.CD_MATERIAL), '[^ ]+', 1, 1), '00:00'), 
              'DD/MM/YYYY HH24:MI') BETWEEN R.DH_INICIO AND R.DH_FIM
    )
    --AND A.IE_STATUS_LOTE IN ('G', 'A', 'E') -- Alinhando com a TV para não omitir os Parciais
    AND A.IE_STATUS_LOTE IN ('G')
    AND M.NR_ATENDIMENTO IS NOT NULL
    AND (A.NR_LOTE_AGRUPAMENTO IS NULL OR A.IE_AGRUPAMENTO = 'S')
    AND OBTER_SE_LOTE_ACM_SN(A.NR_SEQUENCIA, 'SN') = 'N' 
    AND OBTER_SE_LOTE_ACM_SN(A.NR_SEQUENCIA, 'ACM') = 'N'
    AND A.NR_SEQ_CLASSIF != 6
    AND AL.CD_MATERIAL IS NOT NULL
    AND AL.DT_SUPENSAO IS NULL
    AND MAT.IE_TIPO_MATERIAL = 1 -- Medicamento comercial
ORDER BY 
    DT_GERACAO_FULL, -- Ordenamento NATIVO válido com DISTINCT
    DT_ATEND_FULL, 
    NM_PACIENTE, 
    NR_LOTE
    