SELECT DISTINCT
    TO_CHAR(A.DT_GERACAO_LOTE, 'dd/mm/yy') AS DT_GERACAO_LOTE_DATA,
    TO_CHAR(A.DT_GERACAO_LOTE, 'hh24:mi') AS DT_GERACAO_LOTE_HORARIO,
    TO_CHAR(A.DT_ATEND_LOTE, 'dd/mm/yy hh24:mi') AS DT_ATEND_LOTE,
    TO_CHAR(A.DT_LIMITE_INICIO_ATEND, 'dd/mm/yy hh24:mi') AS DT_LIMITE_INICIO_ATEND,
    OBTER_VALOR_DOMINIO(2116, A.IE_STATUS_LOTE) AS DS_STATUS_LOTE,
    A.NR_LOTE_AGRUPAMENTO,
    A.IE_AGRUPAMENTO,
    A.CD_SETOR_ATENDIMENTO,
    SETOR.DS_SETOR_ATENDIMENTO AS DS_SETOR_ATENDIMENTO,
    PF.NM_PESSOA_FISICA AS NM_PACIENTE,
    TO_CHAR(PF.DT_NASCIMENTO, 'dd/mm/yyyy') AS DT_NASCIMENTO,
    SUBSTR(OBTER_DADOS_ATENDIMENTO(M.NR_ATENDIMENTO, 'DE'), 1, 19) AS DT_ENTRADA,
    SUBSTR(OBTER_CONV_CAT_ATENDIMENTO(M.NR_ATENDIMENTO), 1, 255) AS DS_CONVENIO,
    SUBSTR(OBTER_NOME_SETOR(M.CD_SETOR_ATENDIMENTO), 1, 100) AS DS_SETOR,
    SUBSTR(OBTER_UNID_ATEND_SETOR_ATUAL(M.NR_ATENDIMENTO, M.CD_SETOR_ATENDIMENTO, 'U'), 1, 100) AS DS_LEITO,
    A.NR_SEQUENCIA AS NR_LOTE,
    A.NR_PRESCRICAO,
    P.NR_ATENDIMENTO,
    SUBSTR(OBTER_DESC_TURNO_DISP(A.NR_SEQ_TURNO), 1, 80) AS DS_TURNO,
    DECODE(A.NR_SEQ_CLASSIF, 6, 'Agora', 9, 'Ataque', 8, 'Especial', 3, 'Normal', A.NR_SEQ_CLASSIF) AS DS_CLASSIFICACAO,
    -- ADICIONANDO A COLUNA PARA O FILTRO FUNCIONAR
    CASE
        WHEN (OBTER_SE_LOTE_ACM_SN(A.NR_SEQUENCIA, 'SN') = 'S' OR OBTER_SE_LOTE_ACM_SN(A.NR_SEQUENCIA, 'ACM') = 'S') THEN 'S'
        ELSE 'N'
    END AS ACM_SN_FLAG
FROM AP_LOTE A
    LEFT JOIN PRESCR_MEDICA M ON (A.NR_PRESCRICAO = M.NR_PRESCRICAO)
    LEFT JOIN ATENDIMENTO_PACIENTE P ON (M.NR_ATENDIMENTO = P.NR_ATENDIMENTO)
    LEFT JOIN SETOR_ATENDIMENTO_V SETOR ON (SETOR.CD_SETOR_ATENDIMENTO = A.CD_SETOR_ATENDIMENTO)
    LEFT JOIN PESSOA_FISICA PF ON (M.CD_PESSOA_FISICA = PF.CD_PESSOA_FISICA)
WHERE 1=1
    -- FILTRO PARA BUSCAR APENAS LOTES DO DIA CORRENTE
    AND A.DT_ATEND_LOTE >= TRUNC(SYSDATE) AND A.DT_ATEND_LOTE < TRUNC(SYSDATE) + 1
    AND M.NR_ATENDIMENTO IS NOT NULL
    AND A.IE_STATUS_LOTE = 'G'
    AND (A.NR_LOTE_AGRUPAMENTO IS NULL OR A.IE_AGRUPAMENTO = 'S')

     AND (OBTER_SE_LOTE_ACM_SN(A.NR_SEQUENCIA, 'SN') = 'N' AND OBTER_SE_LOTE_ACM_SN(A.NR_SEQUENCIA, 'ACM') = 'N'
         AND A.NR_SEQ_CLASSIF != 6 -- CONDIÇÃO PARA EXCLUIR 'AGORA'
         )
