SELECT     
        A.NR_SEQUENCIA,
        A.NR_SEQUENCIA AS NR_LOTE,
        AL.CD_MATERIAL CD_MATERIAL, 
        SUBSTR(MAT.DS_MATERIAL,1,100) DS_MATERIAL,
        CC.QT_DOSE,
        CC.CD_UNIDADE_MEDIDA_DOSE,
        AL.QT_DISPENSAR, 
        AL.CD_UNIDADE_MEDIDA,
        SUBSTR(OBTER_HORARIO_ITEM_LOTE(A.NR_SEQUENCIA,AL.CD_MATERIAL),1,2000) DS_HORARIO,
        TO_CHAR(M.DT_PRESCRICAO, 'dd/mm/yy hh24:mi') AS DT_PRESCRICAO,
        TO_CHAR(M.DT_LIBERACAO_MEDICO, 'dd/mm/yy hh24:mi') AS DT_LIBERACAO_MEDICO ,
        TO_CHAR(M.DT_LIBERACAO, 'dd/mm/yy hh24:mi') AS DT_LIBERACAO,
        M.IE_RECEM_NATO,
        CC.NR_PRESCRICAO NR_PRESCRICAO_P,
        CC.NR_SEQ_MATERIAL NR_SEQ_MATERIAL_P,   
        (
        SELECT  MAX(BB.CD_LOCAL_ESTOQUE)
        FROM  SETOR_ATENDIMENTO BB,
            PRESCR_MEDICA AA
        WHERE AA.CD_SETOR_ATENDIMENTO = BB.CD_SETOR_ATENDIMENTO
        AND NR_PRESCRICAO = CC.NR_PRESCRICAO
        ) AS CD_LOCAL_ESTOQUE, 
        (   SELECT 
                DS_LOCAL_ESTOQUE  
            FROM LOCAL_ESTOQUE 
            WHERE CD_LOCAL_ESTOQUE = 
            (
                SELECT  
                    MAX(BB.CD_LOCAL_ESTOQUE)
                FROM  SETOR_ATENDIMENTO BB,
                    PRESCR_MEDICA AA
                WHERE AA.CD_SETOR_ATENDIMENTO = BB.CD_SETOR_ATENDIMENTO
                AND NR_PRESCRICAO = CC.NR_PRESCRICAO
            )
        ) AS DS_LOCAL_ESTOQUE   
        , 
        CASE 
                WHEN OBTER_DESC_INTERVALO(PM.CD_INTERVALO) = 'ACM' THEN 'ACM'
                WHEN OBTER_DESC_INTERVALO(PM.CD_INTERVALO) = 'SN' THEN 'SN'
                WHEN OBTER_DESC_INTERVALO(PM.CD_INTERVALO) = 'Agora' THEN 'Agora'
            ELSE 'Não'
            END 
            AS ACM_SN_AGORA,
            DECODE(
                    MAT.IE_RECEITA,
                    'N', 'NÃO',
                    'S', 'SIM'   
                    ) 
                    AS CONTROLADO,
            DECODE(
                    MAT.IE_ALTO_RISCO,
                    'S', 'SIM',
                    'N', 'NÃO'
                    ) AS ALTA_VIGILANCIA

FROM AP_LOTE A
LEFT JOIN PRESCR_MEDICA M ON (A.NR_PRESCRICAO = M.NR_PRESCRICAO )
LEFT JOIN ATENDIMENTO_PACIENTE P ON (M.NR_ATENDIMENTO = P.NR_ATENDIMENTO)
LEFT JOIN SETOR_ATENDIMENTO_V SETOR ON (SETOR.CD_SETOR_ATENDIMENTO = A.CD_SETOR_ATENDIMENTO)
LEFT JOIN PESSOA_FISICA PF ON (M.CD_PESSOA_FISICA = PF.CD_PESSOA_FISICA)
LEFT JOIN AP_LOTE_ITEM AL ON ( AL.NR_SEQ_LOTE = A.NR_SEQUENCIA)
LEFT JOIN PRESCR_MAT_HOR CC ON (AL.NR_SEQ_MAT_HOR = CC.NR_SEQUENCIA)
INNER JOIN MATERIAL MAT ON (MAT.CD_MATERIAL = AL.CD_MATERIAL)
LEFT JOIN PRESCR_MATERIAL PM ON CC.NR_PRESCRICAO = PM.NR_PRESCRICAO AND CC.NR_SEQ_MATERIAL = PM.NR_SEQUENCIA
LEFT JOIN MEDIC_CONTROLADO MC ON MC.CD_MATERIAL = MAT.CD_MATERIAL


WHERE A.IE_STATUS_LOTE IN ('G', 'A', 'E')
  AND M.NR_ATENDIMENTO IS NOT NULL 
    AND AL.CD_MATERIAL IS NOT NULL
    AND AL.DT_SUPENSAO IS NULL
    AND ( A.NR_SEQUENCIA = :NR_LOTE)
    
UNION ALL

SELECT     
        A.NR_SEQUENCIA,
        A.NR_SEQUENCIA AS NR_LOTE,
        AL.CD_MATERIAL CD_MATERIAL, 
        SUBSTR(MAT.DS_MATERIAL,1,100) DS_MATERIAL,
        CC.QT_DOSE,
        CC.CD_UNIDADE_MEDIDA_DOSE,
        AL.QT_DISPENSAR, 
        AL.CD_UNIDADE_MEDIDA,
        SUBSTR(OBTER_HORARIO_ITEM_LOTE(A.NR_SEQUENCIA,AL.CD_MATERIAL),1,2000) DS_HORARIO,
        TO_CHAR(M.DT_PRESCRICAO, 'dd/mm/yy hh24:mi') AS DT_PRESCRICAO,
        TO_CHAR(M.DT_LIBERACAO_MEDICO, 'dd/mm/yy hh24:mi') AS DT_LIBERACAO_MEDICO ,
        TO_CHAR(M.DT_LIBERACAO, 'dd/mm/yy hh24:mi') AS DT_LIBERACAO,
        M.IE_RECEM_NATO,
        CC.NR_PRESCRICAO NR_PRESCRICAO_P,
        CC.NR_SEQ_MATERIAL NR_SEQ_MATERIAL_P,   
        (
        SELECT  MAX(BB.CD_LOCAL_ESTOQUE)
        FROM  SETOR_ATENDIMENTO BB,
            PRESCR_MEDICA AA
        WHERE AA.CD_SETOR_ATENDIMENTO = BB.CD_SETOR_ATENDIMENTO
        AND NR_PRESCRICAO = CC.NR_PRESCRICAO
        ) AS CD_LOCAL_ESTOQUE, 
        (   SELECT 
                DS_LOCAL_ESTOQUE  
            FROM LOCAL_ESTOQUE 
            WHERE CD_LOCAL_ESTOQUE = 
            (
                SELECT  
                    MAX(BB.CD_LOCAL_ESTOQUE)
                FROM  SETOR_ATENDIMENTO BB,
                    PRESCR_MEDICA AA
                WHERE AA.CD_SETOR_ATENDIMENTO = BB.CD_SETOR_ATENDIMENTO
                AND NR_PRESCRICAO = CC.NR_PRESCRICAO
            )
        ) AS DS_LOCAL_ESTOQUE   
        , 
        CASE 
                WHEN OBTER_DESC_INTERVALO(PM.CD_INTERVALO) = 'ACM' THEN 'ACM'
                WHEN OBTER_DESC_INTERVALO(PM.CD_INTERVALO) = 'SN' THEN 'SN'
                WHEN OBTER_DESC_INTERVALO(PM.CD_INTERVALO) = 'Agora' THEN 'Agora'
            ELSE 'Não'
            END 
            AS ACM_SN_AGORA,
            DECODE(
                    MAT.IE_RECEITA,
                    'N', 'NÃO',
                    'S', 'SIM'   
                    ) 
                    AS CONTROLADO,
            DECODE(
                    MAT.IE_ALTO_RISCO,
                    'S', 'SIM',
                    'N', 'NÃO'
                    ) AS ALTA_VIGILANCIA

FROM AP_LOTE A
LEFT JOIN PRESCR_MEDICA M ON (A.NR_PRESCRICAO = M.NR_PRESCRICAO )
LEFT JOIN ATENDIMENTO_PACIENTE P ON (M.NR_ATENDIMENTO = P.NR_ATENDIMENTO)
LEFT JOIN SETOR_ATENDIMENTO_V SETOR ON (SETOR.CD_SETOR_ATENDIMENTO = A.CD_SETOR_ATENDIMENTO)
LEFT JOIN PESSOA_FISICA PF ON (M.CD_PESSOA_FISICA = PF.CD_PESSOA_FISICA)
LEFT JOIN AP_LOTE_ITEM AL ON ( AL.NR_SEQ_LOTE = A.NR_SEQUENCIA)
LEFT JOIN PRESCR_MAT_HOR CC ON (AL.NR_SEQ_MAT_HOR = CC.NR_SEQUENCIA)
INNER JOIN MATERIAL MAT ON (MAT.CD_MATERIAL = AL.CD_MATERIAL)
LEFT JOIN PRESCR_MATERIAL PM ON CC.NR_PRESCRICAO = PM.NR_PRESCRICAO AND CC.NR_SEQ_MATERIAL = PM.NR_SEQUENCIA
LEFT JOIN MEDIC_CONTROLADO MC ON MC.CD_MATERIAL = MAT.CD_MATERIAL


WHERE A.IE_STATUS_LOTE IN ('G', 'A', 'E')
  AND M.NR_ATENDIMENTO IS NOT NULL 
    AND AL.CD_MATERIAL IS NOT NULL
    AND AL.DT_SUPENSAO IS NULL
    AND ( A.NR_LOTE_AGRUPAMENTO = :NR_LOTE)

UNION ALL

SELECT      
        A.NR_SEQUENCIA,
        A.NR_SEQUENCIA AS NR_LOTE,
        AL.CD_MATERIAL CD_MATERIAL,
        SUBSTR(MAT.DS_MATERIAL,1,100) DS_MATERIAL,
        CC.QT_DOSE,
        CC.CD_UNIDADE_MEDIDA_DOSE,
        AL.QT_DISPENSAR, 
        AL.CD_UNIDADE_MEDIDA,
        SUBSTR(OBTER_HORARIO_ITEM_LOTE(A.NR_SEQUENCIA,AL.CD_MATERIAL),1,2000) DS_HORARIO,
        TO_CHAR(M.DT_PRESCRICAO, 'dd/mm/yy hh24:mi') AS DT_PRESCRICAO,
        TO_CHAR(M.DT_LIBERACAO_MEDICO, 'dd/mm/yy hh24:mi') AS DT_LIBERACAO_MEDICO ,
        TO_CHAR(M.DT_LIBERACAO, 'dd/mm/yy hh24:mi') AS DT_LIBERACAO,
        M.IE_RECEM_NATO,
        CC.NR_PRESCRICAO NR_PRESCRICAO_P,
        CC.NR_SEQ_MATERIAL NR_SEQ_MATERIAL_P,
        (
        SELECT  MAX(BB.CD_LOCAL_ESTOQUE)
        FROM  SETOR_ATENDIMENTO BB,
            PRESCR_MEDICA AA
        WHERE AA.CD_SETOR_ATENDIMENTO = BB.CD_SETOR_ATENDIMENTO
        AND NR_PRESCRICAO = CC.NR_PRESCRICAO
        ) AS CD_LOCAL_ESTOQUE,
        (   SELECT
                DS_LOCAL_ESTOQUE
            FROM LOCAL_ESTOQUE
            WHERE CD_LOCAL_ESTOQUE =
            (
                SELECT
                    MAX(BB.CD_LOCAL_ESTOQUE)
                FROM  SETOR_ATENDIMENTO BB,
                    PRESCR_MEDICA AA
                WHERE AA.CD_SETOR_ATENDIMENTO = BB.CD_SETOR_ATENDIMENTO
                AND NR_PRESCRICAO = CC.NR_PRESCRICAO
            )
        ) AS DS_LOCAL_ESTOQUE
        ,
        CASE 
            WHEN OBTER_DESC_INTERVALO(PM.CD_INTERVALO) = 'ACM' THEN 'ACM'
            WHEN OBTER_DESC_INTERVALO(PM.CD_INTERVALO) = 'SN' THEN 'SN'
            WHEN OBTER_DESC_INTERVALO(PM.CD_INTERVALO) = 'Agora' THEN 'Agora'
        ELSE 'Não'
        END 
        AS ACM_SN_AGORA,
        DECODE(
                MC.CD_MATERIAL,
                NULL, 'NÃO',
                MC.CD_MATERIAL, 'SIM'                    
                ) AS CONTROLADO,
        DECODE(
                OBTER_SE_MEDIC_ALTA_VIGILANCIA(MAT.CD_MATERIAL),
                'S', 'SIM',
                'N', 'NÃO'
                ) AS ALTA_VIGILANCIA
FROM PRESCR_MEDICA M
LEFT JOIN AP_LOTE A ON (A.NR_PRESCRICAO = M.NR_PRESCRICAO )
LEFT JOIN ATENDIMENTO_PACIENTE P ON (M.NR_ATENDIMENTO = P.NR_ATENDIMENTO)
LEFT JOIN SETOR_ATENDIMENTO_V SETOR ON (SETOR.CD_SETOR_ATENDIMENTO = A.CD_SETOR_ATENDIMENTO)
LEFT JOIN PESSOA_FISICA PF ON (M.CD_PESSOA_FISICA = PF.CD_PESSOA_FISICA)
LEFT JOIN AP_LOTE_ITEM AL ON ( AL.NR_SEQ_LOTE = A.NR_SEQUENCIA)
LEFT JOIN PRESCR_MAT_HOR CC ON (AL.NR_SEQ_MAT_HOR = CC.NR_SEQUENCIA)
INNER JOIN MATERIAL MAT ON (MAT.CD_MATERIAL = AL.CD_MATERIAL)
LEFT JOIN PRESCR_MATERIAL PM ON CC.NR_PRESCRICAO = PM.NR_PRESCRICAO AND CC.NR_SEQ_MATERIAL = PM.NR_SEQUENCIA
LEFT JOIN MEDIC_CONTROLADO MC ON MC.CD_MATERIAL = MAT.CD_MATERIAL

WHERE M.NR_PRESCRICAO = :NR_PRESCRICAO
AND AL.DT_SUPENSAO IS NULL

AND NOT EXISTS (
    SELECT 1 FROM AP_LOTE A_INNER WHERE A_INNER.NR_SEQUENCIA = :NR_LOTE
)